spring:
  redis:
    host: 192.168.23.130
    port: 6379
#    password: # 默认为空
    database: 0
    timeout: 0
#    redisson:
#      config: classpath:redisson.yml
#    jedis:
#      pool:
#        max-active: 8 # 连接池最大连接数，默认为 8
#        max-idle: 8 # 最大空闲连接数，默认为 8
#        min-idle: 0 # 最小空闲连接数，默认为 0
#        max-wait: -1 # 连接池最大阻塞等待时间，单位：毫秒。默认为 -1，表示不受限制
