server:
  port: 28761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-node2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-node1:18761/eureka/
