server:
  port: 28080

spring:
  application:
    name: client02-consumer

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-node1:18761/eureka/,http://eureka-node2:28761/eureka/