spring:
  datasource:
    url: jdbc:mysql://192.168.23.130:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: mypassword

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.timberliu.springboot.mybatisplus.dataobject

logging:
  level:
    com:
      timberliu:
        springboot:
          mybatisplus:
            mapper: debug